services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - sessions_data:/var/www/storage/framework/sessions
      - cache_data:/var/www/storage/framework/cache
      - views_data:/var/www/storage/framework/views

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: green_it
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  sessions_data:
  cache_data:
  views_data:
volumes:
  - .:/var/www:cached
  - sessions_data:/var/www/storage/framework/sessions
  - cache_data:/var/www/storage/framework/cache
  - views_data:/var/www/storage/framework/views